openapi: 3.0.0
info:
  title: Sales-Person-api
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  /sales-person:
    get:
      summary: get all sales persons
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: ../../models/sales/SalesPerson.v1.yaml
      operationId: get-sales-person
    post:
      summary: create a sales person
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ../../models/sales/SalesPerson.v1.yaml
      operationId: post-sales-person
      requestBody:
        content:
          application/json:
            schema:
              $ref: ../../models/sales/SalesPerson.v1.yaml
  '/sales-person/{salesPersonId}':
    parameters:
      - schema:
          type: string
        name: salesPersonId
        in: path
        required: true
    get:
      summary: get a sales person
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ../../models/sales/SalesPerson.v1.yaml
      operationId: get-sales-person-salesPersonId
    put:
      summary: update a sales perosn
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ../../models/sales/SalesPerson.v1.yaml
      operationId: put-sales-person-salesPersonId
      requestBody:
        content:
          application/json:
            schema:
              $ref: ../../models/sales/SalesPerson.v1.yaml
    delete:
      summary: remove a sales person
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ../../models/sales/SalesPerson.v1.yaml
      operationId: delete-sales-person-salesPersonId
components:
  schemas: {}
