openapi: 3.0.0
info:
  title: Bank Ledger Entries
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  /bank-ledger-entries:
    get:
      summary: Fetch Bank Ledger Entries
      tags:
        - Bank Ledger Entries
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: ../../../models/Finance/Ledger Entries/BankLedgerEntries.v1.yaml
      operationId: get-bank-ledger-entries
components:
  schemas: {}
