openapi: 3.0.0
info:
  title: Bins
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  /bins:
    get:
      summary: Fetches all the bins
      tags:
        - Bin
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: ../../models/Warehouse/Bin.v1.yaml
      operationId: get-bins
      description: ''
    post:
      summary: Create a bin
      tags:
        - Bin
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ../../models/warehouse/Bin.v1.yaml
      operationId: post-bins
      requestBody:
        content:
          application/json:
            schema:
              $ref: ../../models/warehouse/Bin.v1.yaml
  '/bins/{id}/':
    parameters:
      - schema:
          type: string
        name: id
        in: path
        required: true
    get:
      summary: Gets a single bin
      tags:
        - Bin
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ../../models/warehouse/Bin.v1.yaml
      operationId: get-bins-id
    put:
      summary: Updates a single bin
      tags:
        - Bin
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ../../models/warehouse/Bin.v1.yaml
      operationId: put-bins-id
      requestBody:
        content:
          application/json:
            schema:
              $ref: ../../models/warehouse/Bin.v1.yaml
    delete:
      summary: Removes a single bin
      tags:
        - Bin
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ../../models/warehouse/Bin.v1.yaml
      operationId: delete-bins-id
components:
  schemas: {}
