openapi: 3.0.0
info:
  title: Item API
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  /items:
    get:
      summary: get items
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: ../../models/warehouse/Item.v1.yaml
              examples:
                example-1:
                  value:
                    - id: string
                      number: 0
                      name: string
                      category:
                        id: string
                        name: string
                        code: string
                        remarks: string
                      basic_unit_of_measure:
                        id: string
                        code: string
                        name: string
                        remarks: string
                      invintory_qty: 0
                      qty_on_purch_order: 0
                      qty_on_prod_order: 0
                      qty_on_sales_order: 0
                      isBlocked: true
                      costing_method: string
                      unit_cost: 0
                      gen_prod_posting_group: string
                      vat_prod_posting_group: string
                      inventory_posting_group: string
                      sales_price: 0
                      remarks: string
                      warehouse:
                        id: string
                        code: string
                        name: string
                        location:
                          id: string
                          code: string
                          name: string
                          country: string
                          state: string
                        remarks: string
                        bin:
                          id: string
                          code: string
                          name: string
                          remarks: string
                      bin:
                        id: string
                        code: string
                        name: string
                        remarks: string
            application/xml:
              schema:
                $ref: ../../models/warehouse/Item.v1.yaml
      operationId: get-items
    post:
      summary: create item
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ../../models/warehouse/Item.v1.yaml
        '400':
          description: Bad Request
      operationId: post-items
      requestBody:
        content:
          application/json:
            schema:
              $ref: ../../models/warehouse/Item.v1.yaml
  '/items/{itemId}':
    parameters:
      - schema:
          type: string
        name: itemId
        in: path
        required: true
    get:
      summary: get item
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ../../models/warehouse/Item.v1.yaml
        '404':
          description: Not Found
      operationId: get-items-itemId
    put:
      summary: update item
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ../../models/warehouse/Item.v1.yaml
        '400':
          description: Bad Request
        '404':
          description: Not Found
      operationId: put-items-itemId
      requestBody:
        content:
          application/json:
            schema:
              $ref: ../../models/warehouse/Item.v1.yaml
    delete:
      summary: remove item
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ../../models/warehouse/Item.v1.yaml
        '404':
          description: Not Found
      operationId: delete-items-itemId
components:
  schemas: {}
