openapi: 3.0.0
info:
  title: PhysicalInventoryJournal
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  /physical-inverntory-journal:
    get:
      summary: Fetchs all the inventory
      tags:
        - Physical Inventory Journal
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: ../models/warehouse/PhysicalInventoryJournal.v1.yaml
      operationId: get-physical-inverntory-journal
      description: Gets a list of physical inventory journals
    post:
      summary: Creates a physical journal
      tags:
        - Physical Inventory Journal
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ../models/warehouse/PhysicalInventoryJournal.v1.yaml
      operationId: post-physical-inverntory-journal
      description: Creates a single physical inventory journal
      requestBody:
        content:
          application/json:
            schema:
              $ref: ../models/warehouse/PhysicalInventoryJournal.v1.yaml
  '/physical-inverntory-journal/{id}':
    parameters:
      - schema:
          type: string
        name: id
        in: path
        required: true
    get:
      summary: Gets a single physical inventory journal
      tags:
        - Physical Inventory Journal
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ../models/warehouse/PhysicalInventoryJournal.v1.yaml
      operationId: get-physical-inverntory-journal-id
      description: Gets a single physical inventory journal
    put:
      summary: Updates a single physical inventory journal
      tags:
        - Physical Inventory Journal
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ../models/warehouse/PhysicalInventoryJournal.v1.yaml
      operationId: put-physical-inverntory-journal-id
      description: Updates a single physical inventory journal
      requestBody:
        content:
          application/json:
            schema:
              $ref: ../models/warehouse/PhysicalInventoryJournal.v1.yaml
    delete:
      summary: Removes a single physical inventory journal
      tags:
        - Physical Inventory Journal
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ../models/warehouse/PhysicalInventoryJournal.v1.yaml
      operationId: delete-physical-inverntory-journal-id
      description: Removes a single physical inventory journal
components:
  schemas: {}
