openapi: 3.0.0
info:
  title: Sales Return
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  /sales-return:
    get:
      summary: Gets all the sales return
      tags:
        - Sales Return
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: ../../models/Warehouse/SalesReturn.v1.yaml
      operationId: get-sales-return
      description: Gets all the sales returns
    post:
      summary: Create a sales return
      tags:
        - Sales Return
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ../../models/Warehouse/SalesReturn.v1.yaml
      operationId: post-sales-return
      description: Creates a sales return
      requestBody:
        content:
          application/json:
            schema:
              $ref: ../../models/warehouse/SalesReturn.v1.yaml
  '/sales-return/{id}':
    parameters:
      - schema:
          type: string
        name: id
        in: path
        required: true
    get:
      summary: Gets a single sales return
      tags:
        - Sales Return
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ../../models/Warehouse/SalesReturn.v1.yaml
      operationId: get-sales-return-id
      description: Gets a single sales return
    put:
      summary: Updates a single sales return
      tags:
        - Sales Return
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ../../models/Warehouse/SalesReturn.v1.yaml
      operationId: put-sales-return-id
      description: Updates a single sales return
      requestBody:
        content:
          application/json:
            schema:
              $ref: ../../models/warehouse/SalesReturn.v1.yaml
    delete:
      summary: Remove a single sales return
      tags:
        - Sales Return
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ../../models/Warehouse/SalesReturn.v1.yaml
      operationId: delete-sales-return-id
      description: Removes a single sales return
components:
  schemas: {}
