openapi: 3.0.0
info:
  title: StockMovementByLocation
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  /stock-movement-by-location:
    get:
      summary: Gets a list of stock movement by location
      tags:
        - Stock Movement
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: ../../models/Warehouse/StockMovementByLocation.v1.yaml
      operationId: get-stock-movement-by-location
components:
  schemas: {}
