openapi: 3.0.0
info:
  title: UOM Conversion
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  /uom-conversions/:
    get:
      summary: Fetches all the UOM conversions
      tags:
        - UOM
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: ../../models/warehouse/Unit-Measurement-Conversion.v1.yaml
      operationId: get-uom-conversions
    post:
      summary: Creates a UOM conversion
      tags:
        - UOM
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ../../models/warehouse/Unit-Measurement-Conversion.v1.yaml
      operationId: post-uom-conversions
      requestBody:
        content:
          application/json:
            schema:
              $ref: ../../models/warehouse/Unit-Measurement-Conversion.v1.yaml
  '/uom-conversions/{id}/':
    parameters:
      - schema:
          type: string
        name: id
        in: path
        required: true
    get:
      summary: Fetches a single UOM conversion
      tags:
        - UOM
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ../../models/warehouse/Unit-Measurement-Conversion.v1.yaml
      operationId: get-uom-conversions-id
    put:
      summary: Updates a single UOM conversion
      tags:
        - UOM
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ../../models/warehouse/Unit-Measurement-Conversion.v1.yaml
      operationId: put-uom-conversions-id
      requestBody:
        content:
          application/json:
            schema:
              $ref: ../../models/warehouse/Unit-Measurement-Conversion.v1.yaml
    delete:
      summary: Removes a single UOM conversion
      tags:
        - UOM
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ../../models/warehouse/Unit-Measurement-Conversion.v1.yaml
      operationId: delete-uom-conversions-id
components:
  schemas: {}
