openapi: 3.0.0
info:
  title: Warehouse
  version: '1.0'
  description: ''
servers:
  - url: 'http://localhost:3000'
paths:
  /warehouse:
    get:
      summary: Fetches all warehouse
      tags:
        - Warehouse
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: ../../models/warehouse/Warehouse.v1.yaml
      operationId: get-warehouse
    post:
      summary: Creates warehouse
      tags:
        - Warehouse
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ../../models/warehouse/Warehouse.v1.yaml
      operationId: post-warehouse
      requestBody:
        content:
          application/json:
            schema:
              $ref: ../../models/warehouse/Warehouse.v1.yaml
  '/warehouse/{id}':
    parameters:
      - schema:
          type: string
        name: id
        in: path
        required: true
    get:
      summary: Fetches a single warehouse
      tags:
        - Warehouse
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ../../models/warehouse/Warehouse.v1.yaml
      operationId: get-warehouse-id
    put:
      summary: Updates a single warehouse
      tags:
        - Warehouse
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ../../models/warehouse/Warehouse.v1.yaml
      operationId: put-warehouse-id
      requestBody:
        content:
          application/json:
            schema:
              $ref: ../../models/warehouse/Warehouse.v1.yaml
    delete:
      summary: Removes a single warehouse
      tags:
        - Warehouse
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ../../models/warehouse/Warehouse.v1.yaml
      operationId: delete-warehouse-id
components:
  schemas: {}
