openapi: 3.0.0
info:
  title: PurchaseOrder
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  /purchase-orders/:
    get:
      summary: Fetchs all POs
      tags:
        - Purchase
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: ../../models/Purchase/PurchaseOrder.v1.yaml
      operationId: get-purchase-orders
    post:
      summary: Creates a PO
      tags:
        - Purchase
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ../../models/Purchase/PurchaseOrder.v1.yaml
      operationId: post-purchase-orders
      requestBody:
        content:
          application/json:
            schema:
              $ref: ../../models/Purchase/PurchaseOrder.v1.yaml
  '/purchase-orders/{id}':
    parameters:
      - schema:
          type: string
        name: id
        in: path
        required: true
    get:
      summary: Fetches a single PO
      tags:
        - Purchase
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ../../models/Purchase/PurchaseOrder.v1.yaml
      operationId: get-purchase-orders-id
    put:
      summary: Updates a single PO
      tags:
        - Purchase
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ../../models/Purchase/PurchaseOrder.v1.yaml
      operationId: put-purchase-orders-id
      requestBody:
        content:
          application/json:
            schema:
              $ref: ../../models/Purchase/PurchaseOrder.v1.yaml
    delete:
      summary: Remove a single PO
      tags:
        - Purchase
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ../../models/Purchase/PurchaseOrder.v1.yaml
      operationId: delete-purchase-orders-id
  '/purchase-orders/{id}/post':
    parameters:
      - schema:
          type: string
        name: id
        in: path
        required: true
    put:
      summary: Posts PO
      tags:
        - Purchase
      responses: {}
      operationId: put-purchase-orders-id-post
components:
  schemas: {}
