openapi: 3.0.0
info:
  title: FiscalYear
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  /fiscal-years:
    get:
      summary: Fetchs fiscal years
      tags:
        - Fiscal Year
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: ../models/Fiscal-Year.v1.yaml
      operationId: get-fiscal-years
      description: Gets fiscal years
    post:
      summary: Create fiscal year
      tags:
        - Fiscal Year
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ../models/Fiscal-Year.v1.yaml
      operationId: post-fiscal-years
      description: Add fiscal year
      requestBody:
        content:
          application/json:
            schema:
              $ref: ../models/Fiscal-Year.v1.yaml
components:
  schemas: {}
