openapi: 3.0.0
info:
  title: Payment
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  /payments:
    post:
      summary: Create a payment
      tags:
        - Payment
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  date:
                    type: string
                    format: date
                  customer:
                    type: string
                  amount:
                    type: string
                  payment_method:
                    type: string
                  status:
                    type: string
      operationId: post-payments
      description: Creates payment
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                date:
                  type: string
                  format: date
                customer:
                  type: string
                payment_method:
                  type: string
                amount:
                  type: number
components:
  schemas: {}
