openapi: 3.0.0
info:
  title: TrainingPlanning
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  /training-plannings:
    get:
      summary: get all training-plannings
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: ../../models/HR/TrainingPlanning.v1.yaml
      operationId: get-training-plannings
    post:
      summary: create a training-plannings
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ../../models/HR/TrainingPlanning.v1.yaml
      operationId: post-training-plannings
      requestBody:
        content:
          application/json:
            schema:
              $ref: ../../models/HR/TrainingPlanning.v1.yaml
  '/training-plannings/{trainingPlanningId}':
    parameters:
      - schema:
          type: string
        name: trainingPlanningId
        in: path
        required: true
    get:
      summary: get a training-plannings
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ../../models/HR/TrainingPlanning.v1.yaml
      operationId: get-training-plannings-trainingPlanningId
    put:
      summary: update a training-plannings
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ../../models/HR/TrainingPlanning.v1.yaml
      operationId: put-training-plannings-trainingPlanningId
      requestBody:
        content:
          application/json:
            schema:
              $ref: ../../models/HR/TrainingPlanning.v1.yaml
    delete:
      summary: remove a training-plannings
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ../../models/HR/TrainingPlanning.v1.yaml
      operationId: delete-training-plannings-trainingPlanningId
components:
  schemas: {}
