openapi: 3.0.0
info:
  title: Customer API
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  /customers:
    get:
      summary: Get customers
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: ../models/Customer.v1.yaml
      operationId: get-customers
    post:
      summary: Create customer
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ../models/Customer.v1.yaml
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: ../models/Customer.v1.yaml
      operationId: post-customers
      requestBody:
        content:
          application/json:
            schema:
              $ref: ../models/Customer.v1.yaml
  '/customers/{customerId}':
    parameters:
      - schema:
          type: string
        name: customerId
        in: path
        required: true
    get:
      summary: Get customer
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ../models/Customer.v1.yaml
        '404':
          description: Not Found
      operationId: get-customers-customerId
    put:
      summary: Update customer
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ../models/Customer.v1.yaml
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: ../models/Customer.v1.yaml
        '404':
          description: Not Found
      operationId: put-customers-customerId
      requestBody:
        content:
          application/json:
            schema:
              $ref: ../models/Customer.v1.yaml
    delete:
      summary: Remove customer
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ../models/Customer.v1.yaml
        '404':
          description: Not Found
      operationId: delete-customers-customerId
components:
  schemas: {}
