openapi: 3.0.0
info:
  title: General Ledger
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  /general-ledgers/:
    get:
      summary: Fetch all general ledgers
      tags:
        - General Ledger
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: ../models/General-Ledger.v1.yaml
      operationId: get-general-ledgers
      description: Fetch all general ledgers
components:
  schemas: {}
