openapi: 3.0.0
info:
  title: Invoices API
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  /invoices:
    get:
      summary: Get Invoices
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: ../models/Invoice.v1.yaml
      operationId: get-invoice
    post:
      summary: Create Invoice
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ../models/Invoice.v1.yaml
        '400':
          description: Bad Request
      operationId: post-invoice
      requestBody:
        content:
          application/json:
            schema:
              $ref: ../models/Invoice.v1.yaml
    parameters: []
  '/invoices/{invoiceId}':
    parameters:
      - schema:
          type: string
        name: invoiceId
        in: path
        required: true
    get:
      summary: Get Invoice
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ../models/Invoice.v1.yaml
        '404':
          description: Not Found
      operationId: get-invoice-invoiceId
    put:
      summary: Update Inovice
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ../models/Invoice.v1.yaml
        '400':
          description: Bad Request
        '404':
          description: Not Found
      operationId: put-invoice-invoiceId
      requestBody:
        content:
          application/json:
            schema:
              $ref: ../models/Invoice.v1.yaml
    delete:
      summary: Remoce Invoice
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ../models/Invoice.v1.yaml
        '404':
          description: Not Found
      operationId: delete-invoice-invoiceId
components:
  schemas: {}
