openapi: 3.0.0
info:
  title: Trial Balance
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  /trial-balances:
    get:
      summary: Fetches all trial balances
      tags:
        - Trial Balance
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: ../models/Trial-Balance.v1.yaml
      operationId: get-trial-balances
      description: Fetching balances
    post:
      summary: Create a trial balance
      tags:
        - Trial Balance
      responses: {}
      operationId: post-trial-balances
components:
  schemas: {}
