openapi: 3.0.0
info:
  title: CertificationType
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  /certification-types:
    get:
      summary: get all CertificationType
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: ../../../models/HR/Setup/CertificationType.v1.yaml
      operationId: get-certification-types
    post:
      summary: create a CertificationType
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ../../../models/HR/Setup/CertificationType.v1.yaml
      operationId: post-certification-types
      requestBody:
        content:
          application/json:
            schema:
              $ref: ../../../models/HR/Setup/CertificationType.v1.yaml
  '/certification-types/{certificationTypeId}':
    parameters:
      - schema:
          type: string
        name: certificationTypeId
        in: path
        required: true
    get:
      summary: get a CertificationType
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ../../../models/HR/Setup/CertificationType.v1.yaml
      operationId: get-certification-types-certificationTypeId
    put:
      summary: update a CertificationType
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ../../../models/HR/Setup/CertificationType.v1.yaml
      operationId: put-certification-types-certificationTypeId
      requestBody:
        content:
          application/json:
            schema:
              $ref: ../../../models/HR/Setup/CertificationType.v1.yaml
    delete:
      summary: remove a CertificationType
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ../../../models/HR/Setup/CertificationType.v1.yaml
      operationId: delete-certification-types-certificationTypeId
components:
  schemas: {}
