openapi: 3.0.0
info:
  title: Department
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  /departments:
    get:
      summary: get all Department
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: ../../../models/HR/Setup/Department.v1.yaml
      operationId: get-departments
    post:
      summary: create a Department
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ../../../models/HR/Setup/Department.v1.yaml
      operationId: post-departments
      requestBody:
        content:
          application/json:
            schema:
              $ref: ../../../models/HR/Setup/Department.v1.yaml
  '/departments/{departmentId}':
    parameters:
      - schema:
          type: string
        name: departmentId
        in: path
        required: true
    get:
      summary: get a Department
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ../../../models/HR/Setup/Department.v1.yaml
      operationId: get-departments-departmentId
    put:
      summary: update a Department
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ../../../models/HR/Setup/Department.v1.yaml
      operationId: put-departments-departmentId
      requestBody:
        content:
          application/json:
            schema:
              $ref: ../../../models/HR/Setup/Department.v1.yaml
    delete:
      summary: remove a Department
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ../../../models/HR/Setup/Department.v1.yaml
      operationId: delete-departments-departmentId
components:
  schemas: {}
