openapi: 3.0.0
info:
  title: EducationType
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  /education-types:
    get:
      summary: get all EducationType
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: ../../../models/HR/Setup/EducationType.v1.yaml
      operationId: get-education-types
    post:
      summary: create a EducationType
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ../../../models/HR/Setup/EducationType.v1.yaml
      operationId: post-education-types
      requestBody:
        content:
          application/json:
            schema:
              $ref: ../../../models/HR/Setup/EducationType.v1.yaml
  '/education-types/{educationTypeId}':
    parameters:
      - schema:
          type: string
        name: educationTypeId
        in: path
        required: true
    get:
      summary: get a EducationType
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ../../../models/HR/Setup/EducationType.v1.yaml
      operationId: get-education-types-educationTypeId
    put:
      summary: update a EducationType
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ../../../models/HR/Setup/EducationType.v1.yaml
      operationId: put-education-types-educationTypeId
      requestBody:
        content:
          application/json:
            schema:
              $ref: ../../../models/HR/Setup/EducationType.v1.yaml
    delete:
      summary: remove a EducationType
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ../../../models/HR/Setup/EducationType.v1.yaml
      operationId: delete-education-types-educationTypeId
components:
  schemas: {}
