openapi: 3.0.0
info:
  title: GoalType
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  /goal-types:
    get:
      summary: get all GoalType
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: ../../../models/HR/Setup/GoalType.v1.yaml
      operationId: get-goal-types
    post:
      summary: create a GoalType
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ../../../models/HR/Setup/GoalType.v1.yaml
      operationId: post-goal-types
      requestBody:
        content:
          application/json:
            schema:
              $ref: ../../../models/HR/Setup/GoalType.v1.yaml
  '/goal-types/{goalTypeId}':
    parameters:
      - schema:
          type: string
        name: goalTypeId
        in: path
        required: true
    get:
      summary: get a GoalType
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ../../../models/HR/Setup/GoalType.v1.yaml
      operationId: get-goal-types-goalTypeId
    put:
      summary: update a GoalType
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ../../../models/HR/Setup/GoalType.v1.yaml
      operationId: put-goal-types-goalTypeId
      requestBody:
        content:
          application/json:
            schema:
              $ref: ../../../models/HR/Setup/GoalType.v1.yaml
    delete:
      summary: remove a GoalType
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ../../../models/HR/Setup/GoalType.v1.yaml
      operationId: delete-goal-types-goalTypeId
components:
  schemas: {}
