openapi: 3.0.0
info:
  title: IllnessType
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  /illness-types:
    get:
      summary: get all IllnessType
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: ../../../models/HR/Setup/IllnessType.v1.yaml
      operationId: get-illness-types
    post:
      summary: create a IllnessType
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ../../../models/HR/Setup/IllnessType.v1.yaml
      operationId: post-illness-types
      requestBody:
        content:
          application/json:
            schema:
              $ref: ../../../models/HR/Setup/IllnessType.v1.yaml
  '/illness-types/{illnessTypeId}':
    parameters:
      - schema:
          type: string
        name: illnessTypeId
        in: path
        required: true
    get:
      summary: get a IllnessType
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ../../../models/HR/Setup/IllnessType.v1.yaml
      operationId: get-illness-types-illnessTypeId
    put:
      summary: update a IllnessType
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ../../../models/HR/Setup/IllnessType.v1.yaml
      operationId: put-illness-types-illnessTypeId
      requestBody:
        content:
          application/json:
            schema:
              $ref: ../../../models/HR/Setup/IllnessType.v1.yaml
    delete:
      summary: remove a IllnessType
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ../../../models/HR/Setup/IllnessType.v1.yaml
      operationId: delete-illness-types-illnessTypeId
components:
  schemas: {}
