openapi: 3.0.0
info:
  title: Institution
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  /institutions:
    get:
      summary: get all Institution
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: ../../../models/HR/Setup/Institution.v1.yaml
      operationId: get-institutions
    post:
      summary: create a Institution
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ../../../models/HR/Setup/Institution.v1.yaml
      operationId: post-institutions
      requestBody:
        content:
          application/json:
            schema:
              $ref: ../../../models/HR/Setup/Institution.v1.yaml
  '/institutions/{institutionId}':
    parameters:
      - schema:
          type: string
        name: institutionId
        in: path
        required: true
    get:
      summary: get a Institution
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ../../../models/HR/Setup/Institution.v1.yaml
      operationId: get-institutions-institutionId
    put:
      summary: update a Institution
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ../../../models/HR/Setup/Institution.v1.yaml
      operationId: put-institutions-institutionId
      requestBody:
        content:
          application/json:
            schema:
              $ref: ../../../models/HR/Setup/Institution.v1.yaml
    delete:
      summary: remove a Institution
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ../../../models/HR/Setup/Institution.v1.yaml
      operationId: delete-institutions-institutionId
components:
  schemas: {}
