openapi: 3.0.0
info:
  title: Language
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  /languages:
    get:
      summary: get all Language
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: ../../../models/HR/Setup/Language.v1.yaml
      operationId: get-languages
    post:
      summary: create a Language
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ../../../models/HR/Setup/Language.v1.yaml
      operationId: post-languages
      requestBody:
        content:
          application/json:
            schema:
              $ref: ../../../models/HR/Setup/Language.v1.yaml
  '/languages/{languageId}':
    parameters:
      - schema:
          type: string
        name: languageId
        in: path
        required: true
    get:
      summary: get a Language
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ../../../models/HR/Setup/Language.v1.yaml
      operationId: get-languages-languageId
    put:
      summary: update a Language
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ../../../models/HR/Setup/Language.v1.yaml
      operationId: put-languages-languageId
      requestBody:
        content:
          application/json:
            schema:
              $ref: ../../../models/HR/Setup/Language.v1.yaml
    delete:
      summary: remove a Language
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ../../../models/HR/Setup/Language.v1.yaml
      operationId: delete-languages-languageId
components:
  schemas: {}
