openapi: 3.0.0
info:
  title: LeaveType
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  /leave-types:
    get:
      summary: get all LeaveType
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: ../../../models/HR/Setup/LeaveType.v1.yaml
      operationId: get-leave-types
    post:
      summary: create a LeaveType
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ../../../models/HR/Setup/LeaveType.v1.yaml
      operationId: post-leave-types
      requestBody:
        content:
          application/json:
            schema:
              $ref: ../../../models/HR/Setup/LeaveType.v1.yaml
  '/leave-types/{leaveTypeId}':
    parameters:
      - schema:
          type: string
        name: leaveTypeId
        in: path
        required: true
    get:
      summary: get a LeaveType
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ../../../models/HR/Setup/LeaveType.v1.yaml
      operationId: get-leave-types-leaveTypeId
    put:
      summary: update a LeaveType
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ../../../models/HR/Setup/LeaveType.v1.yaml
      operationId: put-leave-types-leaveTypeId
      requestBody:
        content:
          application/json:
            schema:
              $ref: ../../../models/HR/Setup/LeaveType.v1.yaml
    delete:
      summary: remove a LeaveType
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ../../../models/HR/Setup/LeaveType.v1.yaml
      operationId: delete-leave-types-leaveTypeId
components:
  schemas: {}
