openapi: 3.0.0
info:
  title: Nationality
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  /nationalities:
    get:
      summary: get all Nationality
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: ../../../models/HR/Setup/Nationality.v1.yaml
      operationId: get-nationalities
    post:
      summary: create a Nationality
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ../../../models/HR/Setup/Nationality.v1.yaml
      operationId: post-nationalities
      requestBody:
        content:
          application/json:
            schema:
              $ref: ../../../models/HR/Setup/Nationality.v1.yaml
  '/nationalities/{nationalityId}':
    parameters:
      - schema:
          type: string
        name: nationalityId
        in: path
        required: true
    get:
      summary: get a Nationality
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ../../../models/HR/Setup/Nationality.v1.yaml
      operationId: get-nationalities-nationalityId
    put:
      summary: update a Nationality
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ../../../models/HR/Setup/Nationality.v1.yaml
      operationId: put-nationalities-nationalityId
      requestBody:
        content:
          application/json:
            schema:
              $ref: ../../../models/HR/Setup/Nationality.v1.yaml
    delete:
      summary: remove a Nationality
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ../../../models/HR/Setup/Nationality.v1.yaml
      operationId: delete-nationalities-nationalityId
components:
  schemas: {}
