openapi: 3.0.0
info:
  title: Position
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  /positions:
    get:
      summary: get all Position
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: ../../../models/HR/Setup/Position.v1.yaml
      operationId: get-positions
    post:
      summary: create a Position
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ../../../models/HR/Setup/Position.v1.yaml
      operationId: post-positions
      requestBody:
        content:
          application/json:
            schema:
              $ref: ../../../models/HR/Setup/Position.v1.yaml
  '/positions/{positionId}':
    parameters:
      - schema:
          type: string
        name: positionId
        in: path
        required: true
    get:
      summary: get a Position
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ../../../models/HR/Setup/Position.v1.yaml
      operationId: get-positions-positionId
    put:
      summary: update a Position
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ../../../models/HR/Setup/Position.v1.yaml
      operationId: put-positions-positionId
      requestBody:
        content:
          application/json:
            schema:
              $ref: ../../../models/HR/Setup/Position.v1.yaml
    delete:
      summary: remove a Position
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ../../../models/HR/Setup/Position.v1.yaml
      operationId: delete-positions-positionId
components:
  schemas: {}
