openapi: 3.0.0
info:
  title: PositionLevel
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  /position-levels:
    get:
      summary: get all PositionLevel
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: ../../../models/HR/Setup/PositionLevel.v1.yaml
      operationId: get-position-levels
    post:
      summary: create a PositionLevel
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ../../../models/HR/Setup/PositionLevel.v1.yaml
      operationId: post-position-levels
      requestBody:
        content:
          application/json:
            schema:
              $ref: ../../../models/HR/Setup/PositionLevel.v1.yaml
  '/position-levels/{positionLevelId}':
    parameters:
      - schema:
          type: string
        name: positionLevelId
        in: path
        required: true
    get:
      summary: get a PositionLevel
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ../../../models/HR/Setup/PositionLevel.v1.yaml
      operationId: get-position-levels-positionLevelId
    put:
      summary: update a PositionLevel
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ../../../models/HR/Setup/PositionLevel.v1.yaml
      operationId: put-position-levels-positionLevelId
      requestBody:
        content:
          application/json:
            schema:
              $ref: ../../../models/HR/Setup/PositionLevel.v1.yaml
    delete:
      summary: remove a PositionLevel
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ../../../models/HR/Setup/PositionLevel.v1.yaml
      operationId: delete-position-levels-positionLevelId
components:
  schemas: {}
