openapi: 3.0.0
info:
  title: TerminationType
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  /termination-types:
    get:
      summary: get all TerminationType
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: ../../../models/HR/Setup/TerminationType.v1.yaml
      operationId: get-termination-types
    post:
      summary: create a TerminationType
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ../../../models/HR/Setup/TerminationType.v1.yaml
      operationId: post-termination-types
      requestBody:
        content:
          application/json:
            schema:
              $ref: ../../../models/HR/Setup/TerminationType.v1.yaml
  '/termination-types/{terminationTypeId}':
    parameters:
      - schema:
          type: string
        name: terminationTypeId
        in: path
        required: true
    get:
      summary: get a TerminationType
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ../../../models/HR/Setup/TerminationType.v1.yaml
      operationId: get-termination-types-terminationTypeId
    put:
      summary: update a TerminationType
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ../../../models/HR/Setup/TerminationType.v1.yaml
      operationId: put-termination-types-terminationTypeId
      requestBody:
        content:
          application/json:
            schema:
              $ref: ../../../models/HR/Setup/TerminationType.v1.yaml
    delete:
      summary: remove a TerminationType
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ../../../models/HR/Setup/TerminationType.v1.yaml
      operationId: delete-termination-types-terminationTypeId
components:
  schemas: {}
