openapi: 3.0.0
info:
  title: TrainingType
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  /training-types:
    get:
      summary: get all TrainingType
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: ../../../models/HR/Setup/TrainingType.v1.yaml
      operationId: get-training-types
    post:
      summary: create a TrainingType
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ../../../models/HR/Setup/TrainingType.v1.yaml
      operationId: post-training-types
      requestBody:
        content:
          application/json:
            schema:
              $ref: ../../../models/HR/Setup/TrainingType.v1.yaml
  '/training-types/{trainingTypeId}':
    parameters:
      - schema:
          type: string
        name: trainingTypeId
        in: path
        required: true
    get:
      summary: get a TrainingType
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ../../../models/HR/Setup/TrainingType.v1.yaml
      operationId: get-training-types-trainingTypeId
    put:
      summary: update a TrainingType
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ../../../models/HR/Setup/TrainingType.v1.yaml
      operationId: put-training-types-trainingTypeId
      requestBody:
        content:
          application/json:
            schema:
              $ref: ../../../models/HR/Setup/TrainingType.v1.yaml
    delete:
      summary: remove a TrainingType
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ../../../models/HR/Setup/TrainingType.v1.yaml
      operationId: delete-training-types-trainingTypeId
components:
  schemas: {}
